application: emotiongraph
version: 1
runtime: python
api_version: 1

handlers:
- url: /xd_receiver.html
  static_files: static/xd_receiver.html
  upload: static/xd_receiver.html

- url: /blueprint
  static_dir: static/blueprint

- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin/__init__.py
  login: admin
  
- url: /admin
  static_dir: $PYTHON_LIB/google/appengine/ext/admin/template

- url: /(.*\.(gif|png|jpg|ico))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|ico))

- url: /(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
  
- url: /(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /latihan.*
  script: latihan.py
  login: required
  
- url: /trainning.*
  script: trainning.py
  login: required

- url: /graph.*
  script: graph.py
  login: required


- url: /shell.*
  script: shell.py
  login: admin
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

  
- url: /.*
  script: main.py
